version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/app
    container_name: kmw-nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/app
    container_name: kmw-php-fpm
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    container_name: kmw-postgres
    restart: always
    environment:
      - "POSTGRES_DB=kmw"
      - "POSTGRES_USER=bujhm"
      - "POSTGRES_PASSWORD=12345678"
      - "PGDATA=/var/lib/postgresql/data"
    ports:
      - "5432:5432"
